export const VENDOR_DEFAULT_VALUES = {
  userId: "",
  company_name: "",
  company_mobile_number: "",
  company_landline_number: "",
  company_country_id: "",
  company_address1: "",
  company_address2: "",
  company_description: "",
  contact_person_name: "",
  designation: "",
  account_name: "",
  bank_name: "",
  account_number: "",
  company_logo: "",
  company_cover_image: "",
  company_trade_licence: "",
  vendor_passport: "",
  vendor_id: "",
  company_bill: "",
};
